/**
 * Finalize the Glimmer Swiper image library.
 *
 * 1. Wipes the final folders (assets/images/glimmer-swiper/faces & nature)
 * 2. Copies resized images from staging, renaming to face_1..N.jpg / nature_1..N.jpg
 * 3. Regenerates data/glimmerSwiperImages.js with the new counts
 *
 * Run from project root:
 *   node scripts/glimmer-images/finalize.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const STAGING_FACES = path.join(__dirname, 'staging-faces');
const STAGING_NATURE = path.join(__dirname, 'staging-nature-resized');
const FINAL_FACES = path.join(ROOT, 'assets', 'images', 'glimmer-swiper', 'faces');
const FINAL_NATURE = path.join(ROOT, 'assets', 'images', 'glimmer-swiper', 'nature');
const DATA_FILE = path.join(ROOT, 'data', 'glimmerSwiperImages.js');

function wipeAndRecreate(dir) {
  if (fs.existsSync(dir)) {
    for (const f of fs.readdirSync(dir)) fs.unlinkSync(path.join(dir, f));
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function copyRenamed(sourceDir, destDir, prefix) {
  const files = fs
    .readdirSync(sourceDir)
    .filter((f) => /\.jpg$/i.test(f) && !f.startsWith('_'))
    .sort(); // deterministic order
  files.forEach((file, i) => {
    const destName = `${prefix}_${i + 1}.jpg`;
    fs.copyFileSync(path.join(sourceDir, file), path.join(destDir, destName));
  });
  return files.length;
}

function generateDataFile(faceCount, natureCount) {
  const faceEntries = Array.from({ length: faceCount }, (_, i) => {
    const n = i + 1;
    return `  { id: 'face_${n}', source: require('../assets/images/glimmer-swiper/faces/face_${n}.jpg'), category: 'face' },`;
  }).join('\n');

  const natureEntries = Array.from({ length: natureCount }, (_, i) => {
    const n = i + 1;
    return `  { id: 'nature_${n}', source: require('../assets/images/glimmer-swiper/nature/nature_${n}.jpg'), category: 'nature' },`;
  }).join('\n');

  return `/**
 * Glimmer Swiper Image Library
 *
 * Local images bundled with the app for instant loading and offline support.
 * Source: Unsplash (free license, attribution optional — see data/glimmerImageCredits.json).
 *
 * Generated by scripts/glimmer-images/finalize.js. Don't edit by hand —
 * drop new images into the staging folders and rerun the pipeline.
 *
 * Face photos: clearly smiling/happy expressions.
 * Nature photos: calming landscapes (mountains, water, forests, golden hour).
 */

// Smiling faces - diverse, genuine, warm, clearly happy expressions
export const SMILING_FACES = [
${faceEntries}
];

// Nature scenes - calming landscapes, water, forests, sunsets
export const NATURE_SCENES = [
${natureEntries}
];

/**
 * Generate shuffled deck of images for game
 * @param {number} count - Number of images per category
 */
export const generateDeck = (count = 25) => {
  const faces = [...SMILING_FACES].sort(() => Math.random() - 0.5).slice(0, count);
  const nature = [...NATURE_SCENES].sort(() => Math.random() - 0.5).slice(0, count);

  // Interleave faces and nature for balanced gameplay
  const deck = [];
  for (let i = 0; i < count; i++) {
    if (i < faces.length) deck.push(faces[i]);
    if (i < nature.length) deck.push(nature[i]);
  }

  // Final shuffle
  return deck.sort(() => Math.random() - 0.5);
};

/**
 * Get total available images
 */
export const getTotalImages = () => ({
  faces: SMILING_FACES.length,
  nature: NATURE_SCENES.length,
  total: SMILING_FACES.length + NATURE_SCENES.length,
});
`;
}

(function main() {
  console.log('Wiping final folders...');
  wipeAndRecreate(FINAL_FACES);
  wipeAndRecreate(FINAL_NATURE);

  console.log('Copying faces...');
  const faceCount = copyRenamed(STAGING_FACES, FINAL_FACES, 'face');
  console.log(`  ${faceCount} faces -> face_1..face_${faceCount}.jpg`);

  console.log('Copying nature...');
  const natureCount = copyRenamed(STAGING_NATURE, FINAL_NATURE, 'nature');
  console.log(`  ${natureCount} nature -> nature_1..nature_${natureCount}.jpg`);

  console.log('Regenerating data/glimmerSwiperImages.js...');
  fs.writeFileSync(DATA_FILE, generateDataFile(faceCount, natureCount));

  console.log(`\nDone. ${faceCount} faces + ${natureCount} nature = ${faceCount + natureCount} total.`);
})();
