import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { supabase } from './supabase';

const APP_NAME = 'Huxley';
const DIVIDER = '────────────────────────────────────────';

/**
 * Format a date for display
 */
function formatDate(dateStr) {
  if (!dateStr) return 'Unknown date';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  });
}

/**
 * Build the standard header for every share document
 */
function buildHeader(title, date) {
  return [
    `${APP_NAME} — Session Summary`,
    DIVIDER,
    title,
    `Date: ${formatDate(date)}`,
    DIVIDER,
    '',
  ].join('\n');
}

/**
 * Build the standard footer/disclaimer
 */
function buildFooter() {
  return [
    '',
    DIVIDER,
    'This summary was generated by the Huxley integration app.',
    'It reflects the user\'s self-reported experience and AI-guided exploration.',
    'It is not a clinical assessment.',
    DIVIDER,
  ].join('\n');
}

// ═══════════════════════════════════════════════════════════════
// FORMATTERS — one per module type
// ═══════════════════════════════════════════════════════════════

/**
 * Format a Core Beliefs Assessment
 */
function formatCoreBeliefs(data) {
  const domains = [
    ['value_worthiness', 'Value & Worthiness'],
    ['security_safety', 'Security & Safety'],
    ['performance_competence', 'Performance & Competence'],
    ['control_power', 'Control & Power'],
    ['love_nurturance', 'Love & Nurturance'],
    ['autonomy_independence', 'Autonomy & Independence'],
    ['justice_fairness', 'Justice & Fairness'],
    ['belonging_connection', 'Belonging & Connection'],
    ['others_trust', 'Trust in Others'],
    ['standards_compassion', 'Standards & Self-Compassion'],
  ];

  const scores = domains
    .map(([key, label]) => ({ label, score: data[key] }))
    .filter((d) => d.score != null)
    .sort((a, b) => a.score - b.score);

  const lines = [
    buildHeader('Core Beliefs Assessment', data.created_at),
    'DOMAIN SCORES (0-10 scale, lower = more limiting belief)',
    '',
  ];

  scores.forEach(({ label, score }) => {
    const bar = '█'.repeat(Math.round(score)) + '░'.repeat(10 - Math.round(score));
    lines.push(`  ${bar}  ${score.toFixed(1)}  ${label}`);
  });

  const avg = scores.reduce((s, d) => s + d.score, 0) / scores.length;
  lines.push('');
  lines.push(`Overall average: ${avg.toFixed(1)}/10`);

  if (data.discussion_transcript?.length) {
    lines.push('');
    lines.push('DISCUSSION HIGHLIGHTS');
    lines.push('');
    data.discussion_transcript.forEach((msg) => {
      if (typeof msg === 'string') {
        lines.push(`  ${msg}`);
      } else if (msg.content) {
        const prefix = msg.role === 'user' ? 'User' : 'Huxley';
        lines.push(`  ${prefix}: ${msg.content}`);
      }
    });
  }

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format a Nervous System Mapping session
 */
function formatNervousSystem(data) {
  const lines = [
    buildHeader('Nervous System Mapping', data.created_at || data.updated_at),
  ];

  const states = [
    ['ventral', 'Ventral Vagal (Safe & Social)'],
    ['sympathetic', 'Sympathetic (Fight/Flight)'],
    ['dorsal', 'Dorsal Vagal (Shutdown/Freeze)'],
  ];

  states.forEach(([key, label]) => {
    const state = data.state_mappings?.[key] || data[key];
    if (!state) return;
    lines.push(label);
    if (state.body_sensations?.length) {
      lines.push(`  Body sensations: ${state.body_sensations.join(', ')}`);
    }
    if (state.emotions?.length) {
      lines.push(`  Emotions: ${state.emotions.join(', ')}`);
    }
    lines.push('');
  });

  if (data.dominant_state) {
    lines.push(`Dominant state: ${data.dominant_state}`);
  }

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format a Regulating Resources toolkit
 */
function formatRegulatingResources(data) {
  const lines = [
    buildHeader('Regulating Resources Toolkit', data.created_at),
  ];

  const resources = data.state_based_resources || {};

  Object.entries(resources).forEach(([state, categories]) => {
    const stateLabel = {
      sympathetic: 'For Fight/Flight (Sympathetic)',
      dorsal: 'For Shutdown/Freeze (Dorsal)',
      ventral: 'For Maintaining Safety (Ventral)',
    }[state] || state;

    lines.push(stateLabel);
    Object.entries(categories || {}).forEach(([category, items]) => {
      if (items?.length) {
        lines.push(`  ${category}: ${items.join(', ')}`);
      }
    });
    lines.push('');
  });

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format a Daily Journal entry
 */
function formatJournal(data) {
  const lines = [
    buildHeader('Daily Journal Entry', data.created_at),
  ];

  if (data.title) lines.push(`Title: ${data.title}`);
  if (data.mood) lines.push(`Mood: ${data.mood}`);
  if (data.emotions?.length) lines.push(`Emotions: ${data.emotions.join(', ')}`);
  if (data.themes?.length) lines.push(`Themes: ${data.themes.join(', ')}`);
  lines.push('');

  if (data.raw_text) {
    lines.push('JOURNAL CONTENT');
    lines.push('');
    lines.push(data.raw_text);
    lines.push('');
  }

  if (data.insights) {
    lines.push('INSIGHTS');
    lines.push(data.insights);
    lines.push('');
  }

  if (data.gratitude?.length) {
    lines.push('GRATITUDE');
    data.gratitude.forEach((g) => lines.push(`  - ${g}`));
    lines.push('');
  }

  if (data.challenges?.length) {
    lines.push('CHALLENGES');
    data.challenges.forEach((c) => lines.push(`  - ${c}`));
    lines.push('');
  }

  if (data.goals?.length) {
    lines.push('GOALS');
    data.goals.forEach((g) => lines.push(`  - ${g}`));
  }

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format a Set Intention session
 */
function formatIntention(data) {
  const lines = [
    buildHeader('Intention Setting', data.created_at),
  ];

  if (data.intention_text) {
    lines.push('INTENTION');
    lines.push(`  "${data.intention_text}"`);
    lines.push('');
  }

  if (data.framework) lines.push(`Framework: ${data.framework}`);
  if (data.session_type) lines.push(`Session type: ${data.session_type}`);

  if (data.ai_conversation_context) {
    const ctx = data.ai_conversation_context;
    if (ctx.frameworks_explored?.length) {
      lines.push(`Frameworks explored: ${ctx.frameworks_explored.join(', ')}`);
    }
  }

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format an IFS Parts Work session
 */
function formatIFSParts(parts) {
  const lines = [
    buildHeader('IFS Parts Inventory', new Date().toISOString()),
  ];

  if (!parts?.length) {
    lines.push('No parts have been identified yet.');
    lines.push(buildFooter());
    return lines.join('\n');
  }

  parts.forEach((part, i) => {
    lines.push(`${i + 1}. ${part.part_name || 'Unnamed Part'}`);
    if (part.part_role) lines.push(`   Role: ${part.part_role}`);
    if (part.part_feelings) lines.push(`   Feelings: ${part.part_feelings}`);
    if (part.protective_strategy) lines.push(`   Strategy: ${part.protective_strategy}`);
    if (part.location_in_body) lines.push(`   Body location: ${part.location_in_body}`);
    if (part.original_wound_description) lines.push(`   Wound: ${part.original_wound_description}`);
    lines.push('');
  });

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format an Experience Mapping session (conversation)
 */
function formatExperienceMapping(data) {
  const sessionData = data.session_data || data;
  const lines = [
    buildHeader('Experience Processing Session', data.created_at),
  ];

  if (sessionData.sessionType) lines.push(`Type: ${sessionData.sessionType}`);
  lines.push('');

  const messages = sessionData.messages || [];
  if (messages.length) {
    lines.push('CONVERSATION');
    lines.push('');
    messages.forEach((msg) => {
      const role = msg.role === 'user' ? 'User' : 'Huxley';
      lines.push(`${role}:`);
      lines.push(`  ${msg.content}`);
      lines.push('');
    });
  }

  lines.push(buildFooter());
  return lines.join('\n');
}

/**
 * Format a guided exercise completion
 */
function formatExercise(exercise) {
  const lines = [
    buildHeader('Guided Exercise Completed', new Date().toISOString()),
  ];

  lines.push(`Exercise: ${exercise.title || exercise.name}`);
  if (exercise.category) lines.push(`Category: ${exercise.category}`);
  if (exercise.duration) lines.push(`Duration: ${exercise.duration}`);
  if (exercise.description) lines.push(`Description: ${exercise.description}`);
  lines.push('');

  if (exercise.steps?.length) {
    lines.push('STEPS COMPLETED');
    exercise.steps.forEach((step, i) => {
      const text = typeof step === 'string' ? step : step.instruction || step.text;
      lines.push(`  ${i + 1}. ${text}`);
    });
  }

  lines.push(buildFooter());
  return lines.join('\n');
}

// ═══════════════════════════════════════════════════════════════
// FORMAT ALL — combines multiple modules into one document
// ═══════════════════════════════════════════════════════════════

async function formatAll(userId) {
  const sections = [];

  sections.push(`${APP_NAME} — Complete Integration Summary`);
  sections.push(DIVIDER);
  sections.push(`Generated: ${formatDate(new Date().toISOString())}`);
  sections.push(DIVIDER);
  sections.push('');

  // Core Beliefs
  const { data: beliefs } = await supabase
    .from('core_beliefs_assessments')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (beliefs) {
    sections.push('=== CORE BELIEFS ===');
    sections.push(formatCoreBeliefs(beliefs));
    sections.push('');
  }

  // Nervous System
  const { data: nsData } = await supabase
    .from('polyvagal_patterns')
    .select('*')
    .eq('user_id', userId)
    .order('updated_at', { ascending: false })
    .limit(1)
    .single();

  if (nsData) {
    sections.push('=== NERVOUS SYSTEM MAP ===');
    sections.push(formatNervousSystem(nsData));
    sections.push('');
  }

  // Regulating Resources
  const { data: resources } = await supabase
    .from('regulating_resources')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (resources) {
    sections.push('=== REGULATING RESOURCES ===');
    sections.push(formatRegulatingResources(resources));
    sections.push('');
  }

  // IFS Parts
  const { data: parts } = await supabase
    .from('ifs_parts_inventory')
    .select('*')
    .eq('user_id', userId);

  if (parts?.length) {
    sections.push('=== IFS PARTS INVENTORY ===');
    sections.push(formatIFSParts(parts));
    sections.push('');
  }

  // Recent Intentions
  const { data: intentions } = await supabase
    .from('session_intentions')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(3);

  if (intentions?.length) {
    sections.push('=== RECENT INTENTIONS ===');
    intentions.forEach((int) => {
      sections.push(formatIntention(int));
    });
    sections.push('');
  }

  // Recent Journals
  const { data: journals } = await supabase
    .from('daily_journals')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(5);

  if (journals?.length) {
    sections.push('=== RECENT JOURNAL ENTRIES ===');
    journals.forEach((j) => {
      sections.push(formatJournal(j));
    });
  }

  return sections.join('\n');
}

// ═══════════════════════════════════════════════════════════════
// SHARE — write to file and open share sheet
// ═══════════════════════════════════════════════════════════════

/**
 * Share formatted text via the native share sheet.
 *
 * @param {string} text - Formatted summary text
 * @param {string} filename - Filename without extension
 */
async function shareText(text, filename = 'session-summary') {
  const fileUri = `${FileSystem.cacheDirectory}${filename}.txt`;
  await FileSystem.writeAsStringAsync(fileUri, text, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  const canShare = await Sharing.isAvailableAsync();
  if (!canShare) {
    throw new Error('Sharing is not available on this device');
  }

  await Sharing.shareAsync(fileUri, {
    mimeType: 'text/plain',
    dialogTitle: 'Share with Therapist',
    UTI: 'public.plain-text',
  });
}

// ═══════════════════════════════════════════════════════════════
// PUBLIC API
// ═══════════════════════════════════════════════════════════════

export async function shareCoreBeliefs(data) {
  await shareText(formatCoreBeliefs(data), 'core-beliefs-assessment');
}

export async function shareNervousSystem(data) {
  await shareText(formatNervousSystem(data), 'nervous-system-map');
}

export async function shareRegulatingResources(data) {
  await shareText(formatRegulatingResources(data), 'regulating-resources');
}

export async function shareJournal(data) {
  await shareText(formatJournal(data), 'journal-entry');
}

export async function shareIntention(data) {
  await shareText(formatIntention(data), 'intention');
}

export async function shareIFSParts(parts) {
  await shareText(formatIFSParts(parts), 'ifs-parts-inventory');
}

export async function shareExperienceMapping(data) {
  await shareText(formatExperienceMapping(data), 'experience-processing');
}

export async function shareExercise(exercise) {
  await shareText(formatExercise(exercise), 'guided-exercise');
}

export async function shareAll(userId) {
  const text = await formatAll(userId);
  await shareText(text, 'psycheteleos-complete-summary');
}

/**
 * Format a Triggers & Glimmers mapping
 */
function formatTriggersGlimmers(data) {
  const lines = [
    buildHeader('Triggers & Glimmers Map', data.created_at),
  ];

  const triggerGroups = [
    ['sympathetic_triggers', 'Fight / Flight Triggers'],
    ['dorsal_triggers', 'Shutdown Triggers'],
    ['general_triggers', 'General Triggers'],
  ];

  const glimmerGroups = [
    ['sensory_glimmers', 'Sensory Glimmers'],
    ['relational_glimmers', 'Relational Glimmers'],
    ['activity_glimmers', 'Activity Glimmers'],
    ['nature_glimmers', 'Nature Glimmers'],
  ];

  lines.push('TRIGGERS');
  lines.push('');
  triggerGroups.forEach(([key, label]) => {
    const items = data[key];
    if (items?.length) {
      lines.push(`  ${label}:`);
      items.forEach((item) => lines.push(`    - ${item}`));
      lines.push('');
    }
  });

  lines.push('GLIMMERS');
  lines.push('');
  glimmerGroups.forEach(([key, label]) => {
    const items = data[key];
    if (items?.length) {
      lines.push(`  ${label}:`);
      items.forEach((item) => lines.push(`    - ${item}`));
      lines.push('');
    }
  });

  lines.push(buildFooter());
  return lines.join('\n');
}

export async function shareTriggersGlimmers(data) {
  await shareText(formatTriggersGlimmers(data), 'triggers-glimmers');
}

// Export formatters for testing or custom use
export {
  formatCoreBeliefs,
  formatNervousSystem,
  formatRegulatingResources,
  formatJournal,
  formatIntention,
  formatIFSParts,
  formatExperienceMapping,
  formatExercise,
  formatTriggersGlimmers,
  formatAll,
};
