-- ============================================================================
-- FEAT-102: AI Guidance in Set Your Intention Screen - Schema Migration
-- ============================================================================
-- Feature: FEAT-102
-- Version: 1.0
-- Date: 2026-02-10
-- Description: Creates intention templates, session intentions, and user
--              preferences tables for AI-powered intention guidance feature.
-- Depends on: sessions table, auth.users, is_admin() function
-- Privacy: Opt-in storage, encrypted sensitive fields, strict RLS
-- ============================================================================

BEGIN;

-- ============================================================================
-- TABLE 1: intention_templates
-- ============================================================================
-- Purpose: Curated example intentions for user inspiration (app-wide)
-- Access: Read-only for users, admin-only for write
-- Encryption: Not needed (public content)

CREATE TABLE IF NOT EXISTS public.intention_templates (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Content
    title TEXT NOT NULL,
    intention_text TEXT NOT NULL,
    description TEXT,

    -- Categorization
    framework TEXT NOT NULL,
    session_type TEXT NOT NULL,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],

    -- Display
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_featured BOOLEAN DEFAULT FALSE,

    -- Metadata
    example_use_case TEXT,
    therapeutic_notes TEXT,
    source TEXT,

    -- Status
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 1,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT intention_template_title_length CHECK (char_length(title) <= 200),
    CONSTRAINT intention_template_text_length CHECK (char_length(intention_text) <= 1000),
    CONSTRAINT intention_template_desc_length CHECK (char_length(description) <= 500),
    CONSTRAINT intention_template_valid_framework CHECK (
        framework IN (
            'ifs',           -- Internal Family Systems
            'somatic',       -- Somatic/body-based
            'existential',   -- Existential/meaning-making
            'healing',       -- Trauma healing
            'exploration',   -- Open exploration
            'creativity',    -- Creative unblocking
            'spiritual',     -- Spiritual connection
            'integration'    -- Post-session integration
        )
    ),
    CONSTRAINT intention_template_valid_session_type CHECK (
        session_type IN (
            'healing',
            'exploration',
            'creativity',
            'spiritual',
            'integration',
            'general'
        )
    ),
    CONSTRAINT intention_template_positive_sort CHECK (sort_order >= 0),
    CONSTRAINT intention_template_positive_version CHECK (version >= 1)
);

COMMENT ON TABLE public.intention_templates
    IS 'Curated example intentions for user inspiration. Admin-managed, user-readable.';

COMMENT ON COLUMN public.intention_templates.framework
    IS 'Philosophical/therapeutic framework: ifs, somatic, existential, healing, etc.';

COMMENT ON COLUMN public.intention_templates.session_type
    IS 'Type of session this intention is suited for: healing, exploration, creativity, etc.';

COMMENT ON COLUMN public.intention_templates.is_featured
    IS 'Whether to highlight this intention in UI (e.g., homepage carousel).';

COMMENT ON COLUMN public.intention_templates.therapeutic_notes
    IS 'Internal notes for therapists/admins about this intention (not shown to users).';

-- ============================================================================
-- TABLE 2: session_intentions
-- ============================================================================
-- Purpose: User's saved intentions for specific sessions (opt-in storage only)
-- Access: User-only (strict RLS)
-- Encryption: intention_text and ai_conversation_context (encrypted at rest)

CREATE TABLE IF NOT EXISTS public.session_intentions (
    -- Primary Key
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Foreign Keys
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,

    -- Core Content (ENCRYPTED AT REST)
    intention_text TEXT NOT NULL,

    -- Categorization
    framework TEXT,
    session_type TEXT NOT NULL,

    -- AI Metadata (ENCRYPTED AT REST)
    ai_conversation_context JSONB DEFAULT '{}'::JSONB,

    -- User Metadata
    user_rating INTEGER,
    user_notes TEXT,

    -- Derived Insights (optional, generated by AI)
    intention_summary TEXT,
    key_themes TEXT[],

    -- References
    inspired_by_template_id UUID REFERENCES public.intention_templates(id) ON DELETE SET NULL,

    -- Soft Delete
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT session_intentions_text_length CHECK (char_length(intention_text) <= 2000),
    CONSTRAINT session_intentions_summary_length CHECK (char_length(intention_summary) <= 500),
    CONSTRAINT session_intentions_notes_length CHECK (char_length(user_notes) <= 1000),
    CONSTRAINT session_intentions_valid_framework CHECK (
        framework IS NULL OR framework IN (
            'ifs', 'somatic', 'existential', 'healing',
            'exploration', 'creativity', 'spiritual', 'integration'
        )
    ),
    CONSTRAINT session_intentions_valid_session_type CHECK (
        session_type IN (
            'healing', 'exploration', 'creativity',
            'spiritual', 'integration', 'general'
        )
    ),
    CONSTRAINT session_intentions_valid_rating CHECK (
        user_rating IS NULL OR (user_rating >= 1 AND user_rating <= 5)
    ),
    CONSTRAINT session_intentions_deleted_at_requires_flag CHECK (
        (is_deleted = FALSE AND deleted_at IS NULL) OR
        (is_deleted = TRUE AND deleted_at IS NOT NULL)
    )
);

COMMENT ON TABLE public.session_intentions
    IS 'User-saved intentions for sessions. Opt-in storage, encrypted, user-only access.';

COMMENT ON COLUMN public.session_intentions.intention_text
    IS 'ENCRYPTED. The user''s intention text. Max 2000 chars.';

COMMENT ON COLUMN public.session_intentions.ai_conversation_context
    IS 'ENCRYPTED. Stores metadata about AI conversation (not full transcript). Example: {"prompt_count": 3, "frameworks_explored": ["ifs", "somatic"], "session_duration_seconds": 180}';

COMMENT ON COLUMN public.session_intentions.is_deleted
    IS 'Soft delete flag. Allows 30-day recovery window.';

COMMENT ON COLUMN public.session_intentions.user_rating
    IS 'Optional: User rates how helpful this intention was (1-5 stars) after session.';

COMMENT ON COLUMN public.session_intentions.key_themes
    IS 'Optional: AI-extracted themes (e.g., ["grief", "acceptance", "connection"]). Not PII, used for insights.';

-- ============================================================================
-- TABLE 3: user_intention_preferences
-- ============================================================================
-- Purpose: User privacy settings and preferences for intention guidance
-- Access: User-only (strict RLS)
-- Encryption: Not needed (non-sensitive settings)

CREATE TABLE IF NOT EXISTS public.user_intention_preferences (
    -- Primary Key (1:1 with user)
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Privacy Preferences
    save_by_default BOOLEAN NOT NULL DEFAULT FALSE,
    auto_delete_after_days INTEGER,

    -- Feature Preferences
    favorite_frameworks TEXT[] DEFAULT ARRAY[]::TEXT[],
    preferred_session_types TEXT[] DEFAULT ARRAY[]::TEXT[],

    -- AI Preferences
    guidance_style TEXT NOT NULL DEFAULT 'balanced',
    show_examples BOOLEAN NOT NULL DEFAULT TRUE,
    enable_ai_suggestions BOOLEAN NOT NULL DEFAULT TRUE,

    -- Offline Mode
    offline_cache_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    cached_template_ids UUID[] DEFAULT ARRAY[]::UUID[],

    -- Onboarding
    has_completed_onboarding BOOLEAN NOT NULL DEFAULT FALSE,
    onboarding_completed_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT user_intention_prefs_valid_auto_delete CHECK (
        auto_delete_after_days IS NULL OR
        (auto_delete_after_days >= 7 AND auto_delete_after_days <= 365)
    ),
    CONSTRAINT user_intention_prefs_valid_guidance_style CHECK (
        guidance_style IN ('brief', 'balanced', 'detailed')
    ),
    CONSTRAINT user_intention_prefs_onboarding_consistency CHECK (
        (has_completed_onboarding = FALSE AND onboarding_completed_at IS NULL) OR
        (has_completed_onboarding = TRUE AND onboarding_completed_at IS NOT NULL)
    )
);

COMMENT ON TABLE public.user_intention_preferences
    IS 'User preferences for intention guidance feature. One row per user.';

COMMENT ON COLUMN public.user_intention_preferences.save_by_default
    IS 'If TRUE, intentions are saved to database by default (opt-out). If FALSE (default), user must opt-in.';

COMMENT ON COLUMN public.user_intention_preferences.auto_delete_after_days
    IS 'If set, automatically soft-delete intentions older than N days (7-365 range).';

COMMENT ON COLUMN public.user_intention_preferences.guidance_style
    IS 'AI verbosity preference: brief (concise), balanced (default), detailed (thorough).';

COMMENT ON COLUMN public.user_intention_preferences.cached_template_ids
    IS 'Template IDs cached for offline use (max 20).';

-- ============================================================================
-- INDEXES: intention_templates
-- ============================================================================

-- Active templates by framework and session type (most common query)
CREATE INDEX IF NOT EXISTS idx_intention_templates_active_framework_type
    ON public.intention_templates(framework, session_type, sort_order)
    WHERE is_active = TRUE;

-- Featured templates (homepage)
CREATE INDEX IF NOT EXISTS idx_intention_templates_featured
    ON public.intention_templates(sort_order)
    WHERE is_active = TRUE AND is_featured = TRUE;

-- Full-text search on tags (for filtering)
CREATE INDEX IF NOT EXISTS idx_intention_templates_tags
    ON public.intention_templates USING GIN(tags);

-- Admin management (version history)
CREATE INDEX IF NOT EXISTS idx_intention_templates_version_time
    ON public.intention_templates(version, updated_at DESC);

-- ============================================================================
-- INDEXES: session_intentions
-- ============================================================================

-- User's intentions by recency (most common query)
CREATE INDEX IF NOT EXISTS idx_session_intentions_user_time
    ON public.session_intentions(user_id, created_at DESC)
    WHERE is_deleted = FALSE;

-- Session's intentions
CREATE INDEX IF NOT EXISTS idx_session_intentions_session
    ON public.session_intentions(session_id, created_at)
    WHERE is_deleted = FALSE;

-- Soft-deleted intentions (for recovery)
-- Note: can't use NOW() in index predicate (not IMMUTABLE); the 30-day
-- window filter is applied in the query, not here.
CREATE INDEX IF NOT EXISTS idx_session_intentions_deleted
    ON public.session_intentions(user_id, deleted_at DESC)
    WHERE is_deleted = TRUE;

-- Inspired-by tracking (analytics, optional)
CREATE INDEX IF NOT EXISTS idx_session_intentions_template
    ON public.session_intentions(inspired_by_template_id)
    WHERE inspired_by_template_id IS NOT NULL AND is_deleted = FALSE;

-- AI metadata searches (optional, if needed)
CREATE INDEX IF NOT EXISTS idx_session_intentions_ai_context
    ON public.session_intentions USING GIN(ai_conversation_context);

-- ============================================================================
-- ROW LEVEL SECURITY: intention_templates
-- ============================================================================

ALTER TABLE public.intention_templates ENABLE ROW LEVEL SECURITY;

-- Policy 1: Authenticated users can read active templates
CREATE POLICY "Authenticated users can read active intention templates"
    ON public.intention_templates
    FOR SELECT
    USING (
        auth.uid() IS NOT NULL
        AND is_active = TRUE
    );

-- Policy 2: Admins can manage all templates
CREATE POLICY "Admins can manage intention templates"
    ON public.intention_templates
    FOR ALL
    USING (public.is_admin())
    WITH CHECK (public.is_admin());

-- ============================================================================
-- ROW LEVEL SECURITY: session_intentions
-- ============================================================================

ALTER TABLE public.session_intentions ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can view their own intentions (excluding deleted)
CREATE POLICY "Users can view own intentions"
    ON public.session_intentions
    FOR SELECT
    USING (
        auth.uid() = user_id
        AND is_deleted = FALSE
    );

-- Policy 2: Users can view their own deleted intentions (recovery)
CREATE POLICY "Users can view own deleted intentions"
    ON public.session_intentions
    FOR SELECT
    USING (
        auth.uid() = user_id
        AND is_deleted = TRUE
        AND deleted_at > NOW() - INTERVAL '30 days'
    );

-- Policy 3: Users can insert their own intentions
CREATE POLICY "Users can insert own intentions"
    ON public.session_intentions
    FOR INSERT
    WITH CHECK (
        auth.uid() = user_id
        AND (
            session_id IS NULL OR
            session_id IN (
                SELECT id FROM public.sessions WHERE user_id = auth.uid()
            )
        )
    );

-- Policy 4: Users can update their own intentions
CREATE POLICY "Users can update own intentions"
    ON public.session_intentions
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (
        auth.uid() = user_id
        AND (
            session_id IS NULL OR
            session_id IN (
                SELECT id FROM public.sessions WHERE user_id = auth.uid()
            )
        )
    );

-- Policy 5: Admins can view all intentions (for support)
CREATE POLICY "Admins can view all intentions"
    ON public.session_intentions
    FOR SELECT
    USING (public.is_admin());

-- ============================================================================
-- ROW LEVEL SECURITY: user_intention_preferences
-- ============================================================================

ALTER TABLE public.user_intention_preferences ENABLE ROW LEVEL SECURITY;

-- Policy 1: Users can view their own preferences
CREATE POLICY "Users can view own intention preferences"
    ON public.user_intention_preferences
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy 2: Users can insert their own preferences
CREATE POLICY "Users can insert own intention preferences"
    ON public.user_intention_preferences
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy 3: Users can update their own preferences
CREATE POLICY "Users can update own intention preferences"
    ON public.user_intention_preferences
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Policy 4: Admins can view all preferences (for support)
CREATE POLICY "Admins can view all intention preferences"
    ON public.user_intention_preferences
    FOR SELECT
    USING (public.is_admin());

-- ============================================================================
-- FUNCTION: Auto-delete old intentions based on user preferences
-- ============================================================================
-- Purpose: Scheduled job to soft-delete intentions older than user-specified days
-- Usage: Call from scheduled cron job (e.g., daily at midnight)

CREATE OR REPLACE FUNCTION public.auto_delete_old_intentions()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER := 0;
BEGIN
    -- Soft delete intentions based on user preferences
    WITH users_with_auto_delete AS (
        SELECT user_id, auto_delete_after_days
        FROM public.user_intention_preferences
        WHERE auto_delete_after_days IS NOT NULL
    )
    UPDATE public.session_intentions si
    SET
        is_deleted = TRUE,
        deleted_at = NOW(),
        updated_at = NOW()
    FROM users_with_auto_delete uad
    WHERE si.user_id = uad.user_id
      AND si.is_deleted = FALSE
      AND si.created_at < NOW() - (uad.auto_delete_after_days || ' days')::INTERVAL;

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RAISE NOTICE 'Auto-deleted % intentions based on user preferences', deleted_count;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.auto_delete_old_intentions()
    IS 'Soft-deletes intentions older than user-specified auto_delete_after_days. Returns count of deleted intentions.';

-- ============================================================================
-- FUNCTION: Hard delete intentions past recovery window (30 days)
-- ============================================================================
-- Purpose: Permanently delete intentions that have been soft-deleted for >30 days
-- Usage: Call from scheduled cron job (e.g., weekly)

CREATE OR REPLACE FUNCTION public.cleanup_deleted_intentions()
RETURNS INTEGER AS $$
DECLARE
    deleted_count INTEGER := 0;
BEGIN
    -- Permanently delete intentions deleted more than 30 days ago
    DELETE FROM public.session_intentions
    WHERE is_deleted = TRUE
      AND deleted_at < NOW() - INTERVAL '30 days';

    GET DIAGNOSTICS deleted_count = ROW_COUNT;

    RAISE NOTICE 'Permanently deleted % intentions past 30-day recovery window', deleted_count;
    RETURN deleted_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.cleanup_deleted_intentions()
    IS 'Permanently deletes intentions that have been soft-deleted for more than 30 days. Returns count of deleted intentions.';

-- ============================================================================
-- FUNCTION: GDPR-compliant user data deletion
-- ============================================================================
-- Purpose: Delete all intention data for a user (GDPR Right to Erasure)
-- Usage: Called when user requests account deletion

CREATE OR REPLACE FUNCTION public.delete_user_intention_data(target_user_id UUID)
RETURNS void AS $$
BEGIN
    -- Authorization check
    IF auth.uid() != target_user_id AND NOT public.is_admin() THEN
        RAISE EXCEPTION 'Unauthorized: You can only delete your own intention data.';
    END IF;

    -- Delete all intentions (including soft-deleted)
    DELETE FROM public.session_intentions WHERE user_id = target_user_id;

    -- Delete preferences
    DELETE FROM public.user_intention_preferences WHERE user_id = target_user_id;

    RAISE NOTICE 'Deleted all intention data for user %', target_user_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION public.delete_user_intention_data(UUID)
    IS 'GDPR-compliant deletion of user intention data. Permanently deletes all intentions and preferences.';

-- ============================================================================
-- TRIGGER: Auto-update updated_at timestamp
-- ============================================================================

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to session_intentions
CREATE TRIGGER trigger_session_intentions_updated_at
    BEFORE UPDATE ON public.session_intentions
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply to user_intention_preferences
CREATE TRIGGER trigger_user_intention_preferences_updated_at
    BEFORE UPDATE ON public.user_intention_preferences
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Apply to intention_templates
CREATE TRIGGER trigger_intention_templates_updated_at
    BEFORE UPDATE ON public.intention_templates
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ============================================================================
-- SEED DATA: Example Intention Templates
-- ============================================================================

INSERT INTO public.intention_templates
    (title, intention_text, description, framework, session_type, tags, sort_order, is_featured, example_use_case, source)
VALUES
    -- IFS Framework
    ('Meeting the Inner Critic with Compassion',
     'I intend to meet my inner critic with curiosity and compassion, understanding it as a protective part rather than an enemy.',
     'For working with harsh self-judgment using IFS framework',
     'ifs', 'healing',
     ARRAY['inner_critic', 'self_compassion', 'parts_work'],
     10, TRUE,
     'When struggling with self-judgment or harsh internal dialogue',
     'Adapted from IFS therapy'),

    ('Witnessing Exiled Parts',
     'I intend to create a safe space to witness and hold my exiled parts with compassion.',
     'For exploring wounded or hidden parts',
     'ifs', 'healing',
     ARRAY['exile', 'trauma', 'compassion', 'inner_child'],
     20, TRUE,
     'When working with childhood wounds or trauma',
     'IFS principles'),

    ('Understanding Protective Parts',
     'I intend to understand why my protective parts work so hard, and thank them for keeping me safe.',
     'For exploring defensive mechanisms',
     'ifs', 'exploration',
     ARRAY['protectors', 'defense_mechanisms', 'gratitude'],
     30, FALSE,
     'When noticing patterns of avoidance or defensiveness',
     'IFS therapy'),

    -- Somatic Framework
    ('Listening to Body Wisdom',
     'I intend to listen deeply to what my body is trying to tell me, without judgment or rushing to fix.',
     'For connecting with somatic awareness',
     'somatic', 'exploration',
     ARRAY['body_awareness', 'listening', 'presence'],
     40, TRUE,
     'When feeling disconnected from physical sensations',
     'Somatic Experiencing'),

    ('Releasing Held Tension',
     'I intend to notice where tension lives in my body and create space for it to release.',
     'For working with chronic tension or stress',
     'somatic', 'healing',
     ARRAY['tension', 'release', 'nervous_system'],
     50, TRUE,
     'When experiencing chronic pain or stress-related tension',
     'Body-centered therapy'),

    ('Following Sensations',
     'I intend to follow sensations in my body with curiosity, allowing them to guide me.',
     'For somatic exploration',
     'somatic', 'exploration',
     ARRAY['sensations', 'curiosity', 'embodiment'],
     60, FALSE,
     'When wanting to deepen body-mind connection',
     'Somatic practices'),

    -- Existential Framework
    ('Embracing Uncertainty',
     'I intend to sit with uncertainty and not-knowing, trusting that meaning will emerge.',
     'For working with existential anxiety',
     'existential', 'spiritual',
     ARRAY['uncertainty', 'meaning', 'trust'],
     70, TRUE,
     'When facing big life questions or transitions',
     'Existential philosophy'),

    ('Exploring Death Awareness',
     'I intend to explore my relationship with mortality with openness and courage.',
     'For death awareness work',
     'existential', 'spiritual',
     ARRAY['death', 'mortality', 'impermanence', 'courage'],
     80, FALSE,
     'When contemplating mortality or life purpose',
     'Existential psychology'),

    ('Finding Personal Meaning',
     'I intend to explore what truly matters to me, beyond societal expectations.',
     'For values clarification',
     'existential', 'exploration',
     ARRAY['values', 'meaning', 'purpose', 'authenticity'],
     90, TRUE,
     'When questioning life direction or feeling unfulfilled',
     'Logotherapy principles'),

    -- Healing Framework
    ('Healing Grief with Compassion',
     'I intend to approach my grief with compassion, allowing it to move through me at its own pace.',
     'For grief work',
     'healing', 'healing',
     ARRAY['grief', 'loss', 'compassion', 'processing'],
     100, TRUE,
     'When processing loss or bereavement',
     'Grief therapy'),

    ('Forgiving Myself',
     'I intend to explore self-forgiveness and release shame I have been carrying.',
     'For shame and self-forgiveness work',
     'healing', 'healing',
     ARRAY['forgiveness', 'shame', 'self_compassion', 'release'],
     110, TRUE,
     'When struggling with shame or self-blame',
     'Compassion-focused therapy'),

    ('Integrating Trauma',
     'I intend to safely revisit and integrate traumatic experiences with the support of my adult self.',
     'For trauma integration',
     'healing', 'healing',
     ARRAY['trauma', 'integration', 'safety', 'adult_self'],
     120, FALSE,
     'When ready to process past trauma',
     'Trauma-informed practices')

ON CONFLICT DO NOTHING;

COMMIT;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
-- Tables created: 3 (intention_templates, session_intentions, user_intention_preferences)
-- Indexes created: 15
-- RLS policies: 13
-- Functions: 5 (auto_delete, cleanup, GDPR delete, update timestamps)
-- Triggers: 3 (updated_at auto-update)
-- Seed data: 12 example intention templates
-- ============================================================================
